Add scala and sbt versions needed for Gatling tests (#6)
* add sane labels to Dockerfiles

* Add scala and sbt versions needed for Gatling tests

These versions of scala and sbt are needed by the gatling plugin used by
the performance test project.

* Updated sbt Dockerfile to handle diffrent global sbtopts location

As a part of the sbt's docker build, the global sbtopts is modified
("-Dsbt.override.build.repos=true" is appended to it). However, the
location of the sbtopts is different amongst different sbt versions.

At the time of this commit, there are only two possible locations of the
sbtopts across 29 different versions of sbt. The sbt Dockerfile checks
the existence of the sbtopts in these two locations before appending to
it and fails if it does not exist in one of these locations

* add test for scala and sbt new version

* fix changing java_home version

diff --git a/sbt/Dockerfile b/sbt/Dockerfile
--- a/sbt/Dockerfile
+++ b/sbt/Dockerfile
@@ -4,8 +4,12 @@
 #   $ docker run -it onsdigital/jenkins-slave-sbt:0.13.13 sbt -version
 #
 FROM onsdigital/jenkins-slave-scala:2.11.8
-LABEL maintainer="sion.williams@ext.ons.gov.uk" \
-      build-tool="sbt"
+
+ARG TOOL_VERSION
+
+LABEL uk.gov.ons.image.name="jenkins-slave-sbt"
+LABEL uk.gov.ons.image.description="A Jenkins slave with Scala Build Tool"
+LABEL uk.gov.ons.image.version="${TOOL_VERSION}"
 
 
 ENV JENKINS_HOME /home/jenkins
@@ -13,13 +17,22 @@ ENV JENKINS_HOME /home/jenkins
 # build-args are overridden in the docker-compose.yml
 # to allow for multiple builds of new versions from the
 # same dockerfile
-ARG TOOL_VERSION
 ARG MAJOR_MINOR_VERSION
 ARG BASE_URL=https://sbt.bintray.com/rpm/
 
 RUN curl -fsSL -o /tmp/sbt-${TOOL_VERSION}.rpm ${BASE_URL}/sbt-${TOOL_VERSION}.rpm && \
   yum install -y /tmp/sbt-${TOOL_VERSION}.rpm && \
   yum clean all
+
+# The location of global sbtopts is dependent on the version of SBT (rpm) being installed
+# As of 2018/07/24, there are 29 versions of the SBT rpm available on bintray
+# 10 versions use /usr/share/sbt-launcher-packaging/conf    (which is symlinked to /etc/sbt-launcher-packaging)
+# 19 versions use /usr/share/sbt/conf                       (which is symlinked to /etc/sbt)
+# So check for the existence of sbtopts in two locations before appending to it.
+# If none of the two locations exists, exit with non-zero exit code so that the build fails.
+RUN if [ -f /etc/sbt-launcher-packaging/sbtopts ]; then echo "-Dsbt.override.build.repos=true" >> /etc/sbt-launcher-packaging/sbtopts; \
+  elif [ -f /etc/sbt/sbtopts ]; then echo "-Dsbt.override.build.repos=true" >> /etc/sbt/sbtopts; \
+  else exit 1; fi
 
 # Running sbt version here allows us to cache the results of an sbt boot
 # making future executions faster
